### ISSUE TITLE
[Crash] Game fails to start on 1.18.2

### ISSUE THREAD

**Issue by aisukuma** [KxmischesDomi/BoatContainer#10]
I am given a javaRuntimeException when trying to boot up a Minecraft instance with just this mod.

Here is a [crash report](https://gist.github.com/aisukuma/fe925332e94f6a967de8b11b2a60711d) from Boat Container as the latest.log did not provide any useful information.

**Comment by DomiIRL** [comment]
Seems to be a problem with 1.18.2 gonna look into it later

**Comment by DomiIRL** [comment]
I've really got no idea what went wrong there. Its just a simple entity registration :/

**Comment by Razatop** [comment]
Yup having the exact same issue with the same-ish error, want me to go ahead and make a new issue for mine as well or just keep them consolidated?

EDIT: after looking it's the EXACT same error message. No need for me to upload mine unless you'd like it.

**Comment by CYNO-MC** [comment]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'boatcontainer'!
Threw this one just now. Won't let me boot on start. I'm also on 1.18.2

**Comment by DanielFA88** [comment]
Same crash here! :(

**Comment by DomiIRL** [comment]
Should be fixed now!
