### ISSUE TITLE
Boat chest model support / or rotated chest config

### ISSUE THREAD

**Issue by Disketaa** [KxmischesDomi/BoatContainer#14]
Would be nice if boat model would be editable, because I want to rotate the chest inside the boat. Or would be cool just make a config value for chest looking-face.

**Comment by DomiIRL** [comment]
I'm not sure about your first request as minecraft still hasn't made the models made via json as far as I know.
Can't you use optifine to override the model tho? Never used it myself but it works with vanilla mobs so it should as well work with modded ones.
But as for the second request I may add that at a later time

**Comment by Disketaa** [comment]
Thanks
