### ISSUE TITLE
Texture for boat with chest

### ISSUE THREAD

**Issue by Disketaa** [KxmischesDomi/BoatContainer#15]
Hi! I drew a new, smooth texture, if you like it / want, you can feel free to use in your mod.  

![image](https://user-images.githubusercontent.com/76956762/167289938-81876860-5481-45c3-a52b-cbe56a23822c.png)
![image](https://user-images.githubusercontent.com/76956762/167289925-bb459194-fd54-42ca-aaad-6459e31b99ef.png)

Textures:
![chest_boat](https://user-images.githubusercontent.com/76956762/167289981-ed2ddf38-62d3-41ae-b0ef-41b5c23d15eb.png)
![ender_chest_boat](https://user-images.githubusercontent.com/76956762/167289984-e0777370-825b-4e11-a792-0a177cd66258.png)

**Comment by DomiIRL** [comment]
Thank you for your work, I'll think about it!

**Comment by Disketaa** [comment]
Maybe I'll touch them one time for a little. Just to match the square-ish-shape, like minecart with chest

**Comment by Disketaa** [comment]
Hey! What do you think?

![image](https://user-images.githubusercontent.com/76956762/168262285-03499e34-8585-4e5d-956b-1c95c0b3679c.png)

**Comment by DomiIRL** [comment]
Looks nice, could you maybe make one for a furnace? Needing one for a later update maybe ( O_O )

**Comment by Disketaa** [comment]
Oki-doki
Hope furnace boat doesn't burn itself xd

**Comment by Disketaa** [comment]
![image](https://user-images.githubusercontent.com/76956762/168270367-63ec699c-ac34-4b2d-920b-32541e500f65.png)
![image](https://user-images.githubusercontent.com/76956762/168270698-d896fa3b-15f6-47c7-8dde-96c94069d15f.png)

Which is better?

**Comment by DomiIRL** [comment]
bottom because the furnace is not lit by default

**Comment by Disketaa** [comment]
yeah, i know, but lit variant is lit =)

**Comment by Disketaa** [comment]
Take them :)

![chest_boat](https://user-images.githubusercontent.com/76956762/168272180-a4c27ae3-43ce-4ff5-a90f-c2b0e6c0bb63.png)
![ender_chest_boat](https://user-images.githubusercontent.com/76956762/168272185-2c567ab5-c97f-44e7-864b-3291f29cc020.png)
![furnace_boat](https://user-images.githubusercontent.com/76956762/168272188-3743bcf5-6618-4176-93f4-e2d4982f35cf.png)

**Comment by DomiIRL** [comment]
tysm <3

**Comment by Disketaa** [comment]
By the way, I found vanilla boat textures in your assets files. Textures I did works perfectly without them, so If you will replace them textures, you can also remove boat textures from assets to ease customizing/resource-pack-making things tho. 

![image](https://user-images.githubusercontent.com/76956762/168291707-36575c56-d8b1-4511-9485-aab72f05ede1.png)


**Model Item for example**:
```
{
  "parent": "minecraft:item/generated",
  "textures": {
    "layer0": "item/acacia_boat",
    "layer1": "boatcontainer:item/chest_boat"
  }
}
```
