### ISSUE TITLE
Suggestion:  Furnace boats consume their fuel source/coal

### ISSUE THREAD

**Issue by Gl0wstone** [KxmischesDomi/BoatContainer#24]
Would be great to have the furnace boats require new coal after a certain amount of in-game time so they are not overpowered for water transportation. 

e.g. Just an idea....the equivalent energy of a coal block could be left in for two full day-night cycles.  1 piece of coal/energy needed for a 5 minutes of in-game time (25% of 1 day), or 4 coal pieces for a full 20 minute day-night cycle.

**Comment by DomiIRL** [comment]
It is consumed exactly like the furnace minecart consumes its fuel
