### ISSUE TITLE
[Bug] Crafting chest boat makes a furnace boat

### ISSUE THREAD

**Issue by Eatham532** [KxmischesDomi/BoatContainer#25]
Put a chest next to a Dark oak boat and I got a dark oak furnace boat. 

![image](https://user-images.githubusercontent.com/78714349/176413254-c53508b8-43bc-49de-ab1e-6cd820ca75bf.png)

**Comment by DomiIRL** [comment]
Seems like a typo. Thanks gonna fix that ^^
