### ISSUE TITLE
Why...

### ISSUE THREAD

**Issue by Kira-NT** [KxmischesDomi/BoatContainer#27]
https://github.com/KxmischesDomi/BoatContainer/blob/7eacfe1405e024d5b4847e92e2008e0910c61155/src/main/java/de/kxmischesdomi/boatcontainer/mixin/ServerGamePacketListenerImplMixin.java#L24-L28

**Comment by dessader** [comment]
Haha, nice job

**Comment by DomiIRL** [comment]
Thats awkward...

**Comment by Kira-NT** [comment]
Yep, it kinda is :D

**Comment by DomiIRL** [comment]
Okay listen, this was like a five second implementation  (╯°□°)╯

**Comment by Kira-NT** [comment]
I know, don't worry, we all were there :D

**Comment by DomiIRL** [comment]
Nobody talks about this ever again :((

https://github.com/KxmischesDomi/BoatContainer/commit/1bdd5b7387fabe4500755ddf5812d590a1a450cf
