### ISSUE TITLE
furnace in boat not working

### ISSUE THREAD

**Issue by corndoggoiscool** [KxmischesDomi/BoatContainer#31]
chests and ender chests work, but furnaces do not. I press "e" while in the boat (with furnace in it) and it opens my inventory, not the furnace. I exit the boat and shift-right click the furnace, nothing else happens. the mod is the latest version. fabric is updated. nothing is out of date. maybe i'm using a mod that is incompatible with furnaces, but not chests. please respond for any advice.

**Comment by corndoggoiscool** [comment]
sorry, heres an edit of things i forgot to say:
version is 1.19, using curseforge to compile mods, launching in the default minecraft launcher.
i relaunched the game and crafted the items multiple times. they did not work.
thats about it for now

**Comment by DomiIRL** [comment]
The furnace boat is powered by right clicking the boat with coal or charcoal exactly like the furnace minecart.

**Comment by corndoggoiscool** [comment]
@KxmischesDomi can you put ores/smeltable materials in it?

**Comment by DomiIRL** [comment]
> @KxmischesDomi can you put ores/smeltable materials in it?

No its not made for that purpose

**Comment by corndoggoiscool** [comment]
@KxmischesDomi alright. thank you!
