### ISSUE TITLE
Parsing error loading recipe boatcontainer:stripped_bamboo_ender_chest_boat

### ISSUE THREAD

**Issue by giuliotoplad** [KxmischesDomi/BoatContainer#32]
Boat Container Version: 1.2.2 for 1.18

Minecraft Version: 1.18.2

Fabric Version: 0.14.9

Description: When I load the Server they give me an error on loading the bamboo ender chest, here's the full log:
[latest.log](https://github.com/KxmischesDomi/BoatContainer/files/9457094/latest.log)
If you don't want to download the log file: https://pastebin.com/tEKgHWku

**Comment by DomiIRL** [comment]
Yeah I know about thats. Minecraft gives an error if an item from a recipe isn't found.
I will have to load them per code in a future update.

**Comment by giuliotoplad** [comment]
> Yeah I know about thats. Minecraft gives an error if an item from a recipe isn't found. I will have to load them per code in a future update.

Thank you, when is out just close the issue so I receive the notification and test it

**Comment by DomiIRL** [comment]
It should be updated now and fixed so Imma close the issue

**Comment by giuliotoplad** [comment]
Boat Container Version: 1.2.3 for 1.18
Minecraft Version: 1.18.2
Fabric Version: 0.14.9
________________________________________________________
Description: Same thing of the version before but this time the error comes for only one recipe: boatcontainer:stripped_bamboo_chest_boat
________________________________________________________
Download Log: 
[latest.log](https://github.com/KxmischesDomi/BoatContainer/files/9499863/latest.log)
________________________________________________________
View Log: 
https://pastebin.com/AtniHQ1X

**Comment by DomiIRL** [comment]
> Boat Container Version: 1.2.3 for 1.18 Minecraft Version: 1.18.2 Fabric Version: 0.14.9
> 
> Description: Same thing of the version before but this time the error is for one only recipe and not two recipes
> 
> Download Log: [latest.log](https://github.com/KxmischesDomi/BoatContainer/files/9499863/latest.log)
> 
> View Log: https://pastebin.com/AtniHQ1X

This is really weird. It shouldn't try to add it without twigs installed...

**Comment by DomiIRL** [comment]
Imma look over that tomorrow ^^

**Comment by giuliotoplad** [comment]
> Imma look over that tomorrow ^^

Thank you, just like you did before when the updates come close the issue so I can retest it

**Comment by DomiIRL** [comment]
@giuliotoplad I found the issue. Apparently I forgot to delete the old recipe files on 1.18 and 1.17 .-.

**Comment by giuliotoplad** [comment]
> @giuliotoplad I found the issue. Apparently I forgot to delete the old recipe files on 1.18 and 1.17 .-.

Thank you a lot for your patience, I downloaded the new version and test it
I can assure that the issue has been fixed so I'm going to close the issue

**Comment by DomiIRL** [comment]
> > @giuliotoplad I found the issue. Apparently I forgot to delete the old recipe files on 1.18 and 1.17 .-.
> 
> Thank you a lot for your patience, I downloaded the new version and test it I can assure that the issue has been fixed so I'm going to close the issue

I'm glad it works now ^^
Literally did it in school xd
