### ISSUE TITLE
Suggestion: Furnace Chests

### ISSUE THREAD

**Issue by CyborgCabbage** [KxmischesDomi/BoatContainer#7]
I was going along in a boat in AOF5 and I thought it would be neat if you could make it faster by adding a furnace (just like furnace minecarts). It would be a tradeoff, you can't have a chest if you have a furnace. Would probably also want to make it so it doesn't do anything on ice, otherwise the speed might get insane. Of course you may consider this beyond the scope of your mod

**Comment by DomiIRL** [comment]
Added ;D
